name: Build and Test
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - go_version: "1.15"
          - go_version: "1.16"
    services:
      postgres:
        image: ghcr.io/infrastructure-as-code/postgres:12-alpine
        env:
          SSL_ONLY: "false"
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: p0stgr3s
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-go@v2
        name: Setup Go
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install buffalo
        run: |
          go get github.com/gobuffalo/buffalo/buffalo
          go mod download
          buffalo version

      - name: build and run test
        run: |
          buffalo test
        env:
          TEST_DATABASE_URL: postgres://postgres:p0stgr3s@localhost:5432/buffalo_test_database
